services:
  postgres:
    image: postgres
    container_name: expenseTrackerdb
    ports:
      - "5432:5432" # left side is host, right side is container
    restart: always
    volumes:
      - expenseTrackerdb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  expenseTrackerdb_data:
